{% set version = "6.0.0" %}
package:
  name: testfixtures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/testfixtures/testfixtures-{{ version }}.tar.gz
  sha256: f6c4cf24d043f9d8e9a9337371ec1d2f6638a0032504bd67dbd724224fd64969

build:
  number: 1
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - testfixtures
    - testfixtures.tests
    - testfixtures.tests.test_django

about:
    home: https://testfixtures.readthedocs.io
    license: MIT
    license_file: LICENSE.txt
    summary: 'A collection of helpers and mock objects for unit tests and doc tests.'
    doc_url: https://testfixtures.readthedocs.io
    dev_url: https://github.com/Simplistix/testfixtures

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
    - cjw296
   
