travis:
  secure:
    BINSTAR_TOKEN: pCu/KEhCARIDL+tSwVq43UJg3jkTGrUNN/LWDQ7nLrM2rHTxwGe6Umelhhe4NlYxZW5baYHRfYCY9joIt6jltXDj+6BcVSeuwQ6th/wSViToLMunJ4u4BppVhte8Ve4dZW3siejK2vH72lusztkIbO+8gVWe9+7jeqGr6cbmtInplp8B4BqmIa9a3Nn4+cPZLyTg00LPTUpZiW6N/MgFt8Mb3OYSV+ET8XvVBeaoiYg9TK7nJATah8fl4j/ooFWc/2gKUjSnakWALdiqJJJJCXKr1Nz3scVxfQhJ9BXrk+3T2jBoiM3lRCf3MPNFblVuw2ZKIoSsvOYr3Nww9yzLa+fQHuHSLKjVq1n0wYqcwgoCwg22Qx7rT05FQntRXGwOeEB0V3q2j45zDwM3osPjCL/PX0lxqksmbzBIS/57t0J4Umg3wABqiIQkTWgEEcvN221v4u0tEIO7IS8kLYtIxUhmd+Yxdn+xuzFH+EHDewVkNwv+li7YeOdnrnsqL259AiZnbr1WseDrOSX3FeYd8e8VX33I6rkr3dEDtDhhZn6/DRKJtH4dLN+4XUsMKJ2AGBOJas3DaY7p4gFJFmwgSlrJOIfyqGFif0qayjvbxmOSw0+K2UXGSBBQjgiLnOjV7jF7EjDXhkXJdLJOWugOvJ89yj9PQ0y1qukahre1gVU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
